var grunt = require('grunt');
var path = require('path');

exports.wrap = function(content, filePath, options) {
	var moduleStr = "// This file is automatically generated. Please, edit corresponding template instead.\n" +
	"define(['ember'], function() {\n" +
	content +
	"\n});"

    if (options.banner) {
        moduleStr = "// " + options.banner + "\n" + moduleStr;
    }

	return moduleStr;
}
